In [1]:
import pandas as pd

# Завдання 1. Побудова wide-таблиці для Варіанта 2 (Львів)
wide = pd.DataFrame({
    "місто": ["Львів"],
    "Січ": [82],
    "Лют": [78],
    "Бер": [72],
    "Кві": [62],
    "Тра": [55],
    "Чер": [48],
    "Лип": [44],
    "Сер": [46],
    "Вер": [56],
    "Жов": [70],
    "Лис": [80],
    "Гру": [85]
})

print("Wide-таблиця:")
display(wide)

Wide-таблиця:

   місто  Січ  Лют  Бер  Кві  Тра  Чер  Лип  Сер  Вер  Жов  Лис  Гру
0  Львів   82   78   72   62   55   48   44   46   56   70   80   85

In [2]:
# Завдання 2. Приведення до tidy-формату
tidy = wide.melt(id_vars="місто", var_name="місяць", value_name="хмарність")

print("Tidy-таблиця:")
display(tidy)
print("Форма (shape) результату:", tidy.shape)

Tidy-таблиця:

    місто місяць  хмарність
0   Львів    Січ         82
1   Львів    Лют         78
2   Львів    Бер         72
3   Львів    Кві         62
4   Львів    Тра         55
5   Львів    Чер         48
6   Львів    Лип         44
7   Львів    Сер         46
8   Львів    Вер         56
9   Львів    Жов         70
10  Львів    Лис         80
11  Львів    Гру         85

Форма (shape) результату: (12, 3)

### Завдання 3. Класифікація змінних
* **місто** — номінальна шкала: це категоріальна змінна, яка називає об'єкт без жодного природного чи кількісного порядку.
* **місяць** — порядкова (або циклічна) шкала: значення утворюють чітку хронологічну послідовність протягом року (від січня до грудня).
* **хмарність** — шкала відношень: відсотки мають фіксований і реальний абсолютний нуль (0% означає повну відсутність хмарності), а співвідношення між значеннями мають математичний сенс.

In [3]:
# Завдання 4. Зворотне перетворення (tidy -> wide)
back = tidy.pivot(index="місто", columns="місяць", values="хмарність").reset_index()

print("Відновлена wide-таблиця:")
display(back)

Відновлена wide-таблиця:

місяць  місто  Бер  Вер  Гру  Жов  Кві  Лип  Лис  Лют  Сер  Січ  Тра  Чер
0       Львів   72   56   85   70   62   44   80   78   46   82   55   48

In [4]:
# Завдання 5. Запис у файли
tidy.to_csv("variant.csv", index=False)
tidy.to_json("variant.json", orient="records", force_ascii=False)

# Читання назад
reloaded_csv = pd.read_csv("variant.csv")
reloaded_json = pd.read_json("variant.json")

print(" CSV успішно завантажено. Форма:", reloaded_csv.shape)
print(" JSON успішно завантажено. Форма:", reloaded_json.shape)

 CSV успішно завантажено. Форма: (12, 3)
 JSON успішно завантажено. Форма: (12, 3)

### Відповіді на контрольні запитання

1. **Чому стовпець "місто" — номінальна шкала, а стовпець "хмарність" — шкала відношень?**
   Стовпець "місто" є номінальною шкалою, оскільки назви міст слугують лише мітками категорій без будь-якого кількісного порядку чи ранжування. Стовпець "хмарність" вимірюється у відсотках і має абсолютний нуль (0% означає фізичну відсутність хмарності), а також дозволяє коректно порівнювати значення через їх кратність (наприклад, 80% — це вдвічі більше за 40%), що відповідає шкалі відношень.

2. **Чому вихідна wide-таблиця з місяцями в стовпцях не вважається tidy, і що саме змінюється в її структурі після melt()?**
   Wide-таблиця не є tidy, оскільки назви змінних (місяці) заховані в заголовках стовпців, а не записані як окремі значення в одному стовпці. Після застосування `melt()` структура змінюється так, що кожен рядок починає відповідати одному спостереженню (пара "місто — місяць"), що робить таблицю зручною для фільтрації, групування та аналізу в бібліотеках на кшталт pandas чи seaborn.

3. **Чим формат CSV принципово відрізняється від JSON при зберіганні однієї й тієї самої таблиці?**
   CSV (Comma-Separated Values) — це плоский текстовий формат, де дані організовані у вигляді таблиці рядків і стовпців, розділених комами, без збереження метаданих про типи даних (усе зберігається як текст чи числа безпосередньо). Натомість JSON (JavaScript Object Notation) — це ієрархічний формат структур даних (у нашому випадку — масив об'єктів/словників), який явно описує ключі й значення, що робить його більш гнучким для вкладених або нерегулярних даних, але дещо важкозчитуваним "очима" у порівнянні з простими таблицями CSV.